services:
  server:
    build:
      context: server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    command: npm run dev
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
      - ./db/init_data:/docker-entrypoint-initdb.d
volumes:
  database:

